---
- name: Deploy a Docker container
  hosts: all
  become: yes
  tasks:
    - name: Ensure apt-get is not locked
      ansible.builtin.shell: |
        rm -f /var/lib/dpkg/lock
        rm -f /var/lib/dpkg/lock-frontend
        rm -f /var/cache/apt/archives/lock
    
    - name: Install Docker prerequisites
      ansible.builtin.apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg-agent
          - software-properties-common
        state: present
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: Add Docker GPG key
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/debian/gpg
        state: present
      when: ansible_os_family == "Debian"

    - name: Add Docker repository
      ansible.builtin.apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable"
        state: present
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: Install Docker packages
      ansible.builtin.apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: present
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: Ensure Docker is running
      ansible.builtin.service:
        name: docker
        state: started
        enabled: yes

    - name: Pull the latest container image
      community.docker.docker_image:
        name: reethu2/sample4:latest
        source: pull

    - name: Run the container
      community.docker.docker_container:
        name: my-app-container
        image: reethu2/sample4:latest
        state: started
        recreate: yes
        ports:
          - "80:80"
